version: '3.8'

services:
    auth-server:
        build:
            context: .
            dockerfile: ./apps/auth-server/Dockerfile
        env_file:
            - .env
        ports:
            - '8000:8000'
        volumes:
            - ./apps/auth-server:/app/apps/auth-server
            - /app/apps/auth-server/node_modules
        command: yarn workspace @stream-as-it/auth-server run dev
    stream-manager:
        build:
            context: .
            dockerfile: ./apps/stream-manager/Dockerfile
        env_file:
            - .env
        ports:
            - '8001:8001'
        volumes:
            - ./apps/stream-manager:/app/apps/stream-manager
            - /app/apps/stream-manager/node_modules
        command: yarn workspace @stream-as-it/stream-manager run dev
    stream-as-it-psql:
        image: postgres
        env_file:
            - .env
        ports:
            - '5432:5432'

networks:
    default:
