version: '3.8'

services:
    auth-server:
        build:
            context: .
            dockerfile: ./apps/auth-server/Dockerfile
            args:
                APP: '@stream-as-it/auth-server'
                OUT: 'auth-server'
        env_file:
            - .env
        ports:
            - '8000:8000'
        volumes:
            - ./apps/auth-server:/app/apps/auth-server
            - /app/apps/auth-server/node_modules
        command: yarn workspace @stream-as-it/auth-server run dev
    stream-as-it-psql:
        image: postgres
        env_file:
            - .env
        ports:
            - '5432:5432'

networks:
    default:
